=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/schema/prosecution.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/prosecution.json",
  "type": "object",
  "description": "Prosecution Case File Details",
  "properties": {
    "caseDetails": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/case-details.json"
    },
    "defendants": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/defendant.json"
      }
    },
    "channel": {
      "type": "string",
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/pcf-definitions.json#/definitions/channel"
    },
    "listNewHearing": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/hearingRequest.json"
    },
    "migrationSourceSystem": {
      "$ref": "http://justice.gov.uk/core/courts/migrationSourceSystem.json"
    },
    "externalId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid",
      "description": "ID originating from the client (SPI or CPPI) for referencing the original message"
    },
    "isCivil": {
      "description": "Marker to indicate that MoJ offence reference data should be used as opposed to criminal offence reference data",
      "type": "boolean"
    },
    "isGroupMember": {
      "description": "Indicates if a case is part of a group of cases within the hearing",
      "type": "boolean"
    },
    "isGroupMaster": {
      "description": "Indicates which case within a group (isGroupMember = true) is the master and should be returned by the backend to the UI",
      "type": "boolean"
    }
  },
  "required": [
    "caseDetails",
    "defendants",
    "channel"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-civil-charge-past-hearing-date.json
{
  "caseDetails": {
    "initiationCode": "O",
    "prosecutor": {
      "prosecutingAuthority": "prosAut"
    },
    "originatingOrganisation": "GAFTL00",
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "custodyStatus": "B",
      "individual": {
        "personalInformation": {
          "address": {
            "address1": "340",
            "address2": "8009 Camden Throughway",
            "postcode": "SW11 1JU"
          },
          "title": "Mr",
          "firstName": "TyshawnTEST",
          "lastName": "O'Reilly"
        },
        "selfDefinedInformation": {
          "dateOfBirth": "2050-02-04",
          "gender": "NOT_SPECIFIED",
          "nationality": "ZZZ"
        },
        "parentGuardianInformation": {
          "dateOfBirth": "2050-02-04",
          "gender": "MALE"
        }
      },
      "documentationLanguage": "E",
      "hearingLanguage": "E",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "2013c181-7458-4fb2-a637-b596fbe0e792",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "arrestDate": "2015-03-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          }
        }
      ],
      "initialHearing": {
        "hearingDuration": 20,
        "hearingLanguage": "E",
        "dateOfHearing": "2020-01-01",
        "timeOfHearing": "11:11:00.000",
        "courtHearingLocation": "BADLOC",
        "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8"
      },
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1"
    }
  ],
  "channel": "CIVIL",
  "isCivil": true
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-sjp-prosecution-when-prosecutor-is-valid.json
{
  "caseDetails":{
    "caseId":"CASE-ID",
    "initiationCode":"J",
    "prosecutorCaseReference":"nPGQG9oQw3",
    "originatingOrganisation":"GAEAA01",
    "cpsOrganisation": "A30AB00",
    "prosecutor":{
      "prosecutingAuthority":"GAEAA01",
      "informant":"Venu"
    }
  },
  "defendants":[
    {
      "asn":"asn",
      "documentationLanguage":"E",
      "hearingLanguage":"E",
      "id":"cc71424a-cc98-4dda-828f-eb3e31b075c8",
      "individual":{
        "driverNumber":"AS",
        "nationalInsuranceNumber":"SN123456C",
        "personalInformation":{
          "address":{
            "address1":"Address Line 1",
            "address2":"Address Line 2",
            "address3":"Address Line 3",
            "address4":"Address Line 4",
            "address5":"Address Line 5",
            "postcode":"CR0 1XX"
          },
          "contactDetails":{
            "home":"9991231230",
            "mobile":"9991231230",
            "primaryEmail":"abc@test.com",
            "secondaryEmail":"abc@test.com",
            "work":"9991231230"
          },
          "firstName":"Steve  nothing",
          "lastName":"Reaper",
          "occupation":"TA",
          "occupationCode":666,
          "title":"Baron"
        },
        "selfDefinedInformation":{
          "additionalNationality":"GBR",
          "dateOfBirth":"1999-09-09",
          "ethnicity":"W1",
          "gender":"MALE",
          "nationality":"POL"
        }
      },
      "languageRequirement":"Test no special language needs",
      "numPreviousConvictions":9,
      "offences":[
        {
          "appliedCompensation":0.00,
          "backDuty":0.00,
          "backDutyDateTo":"2019-12-04",
          "chargeDate":"2019-12-04",
          "offenceCode":"CA03013",
          "offenceCommittedDate":"2019-11-04",
          "offenceCommittedEndDate":"2019-12-04",
          "offenceDateCode":4,
          "offenceId":"0572d1d1-97ff-4eb8-87da-601334d543d6",
          "offenceLocation":"Croydon",
          "offenceSequenceNumber":1,
          "offenceWording":"Test Prosecution charge wording",
          "offenceWordingWelsh":"Test Prosecution charge wording in Welsh",
          "statementOfFacts":"Test Prosecution statements of facts"
        }
      ],
      "postingDate":"2019-12-04",
      "prosecutorDefendantReference":"397e6282-21b7-4220-aa75-102dd4569111",
      "specificRequirements":"Test no special needs",
      "appliedProsecutorCosts":20.99
    }
  ],
  "channel":"CPPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-cppi-second-message.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "summonsCode": "A",
    "caseId": "CASE-ID",
    "initiationCode": "INITIATION_CODE",
    "prosecutorCaseReference": "CASE-URN",
    "policeSystemId": "00101PoliceCaseSystem",
    "caseMarkers": [
      {
        "markerTypeCode": "ABC",
        "markerTypeDescription": "",
        "markerTypeId": "2013c181-7458-4fb2-a637-b596fbe0e781"
      }
    ],
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    },
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID3",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE3",
      "individualAliases": [
        {
          "title": "Baron",
          "firstName": "John",
          "givenName2": "James",
          "givenName3": "Jerry",
          "lastName": "Smith"
        },
        {
          "title": "Baroness",
          "firstName": "John",
          "lastName": "Smith"
        }
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "bailConditions": "bailConditions",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "Alice",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "bailConditions": "bailConditions",
        "selfDefinedInformation": {
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID3",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-10-10",
          "arrestDate": "2018-10-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Toyota",
          "vehicleRegistrationMark": "BB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-mcc-summons-fixed-past-earliest-date.json
{
  "caseDetails": {
    "dateReceived": "2018-07-10",
    "trialReceiptType": "Transfer",
    "eitherWayType": "Election of accused",
    "courtReceivedFromCode": "B02NM03",
    "courtReceivedToCode": "B04NM04",
    "classOfCase": "Class 1",
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Mr"
      }
    },
    "initiationCode": "S",
    "prosecutor": {
      "prosecutingAuthority": "prosAut"
    },
    "policeForceCode": "1"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "pncIdentifier": "2099/1234567L",
      "croNumber": "SF20/123456M",
      "prosecutorDefendantReference": "TFL001Defendant01",
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "numPreviousConvictions": 3,
      "individual": {
        "personalInformation": {
          "title": "Mr",
          "firstName": "John",
          "lastName": "Smith",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        },
        "bailConditions": "bailConditions",
        "parentGuardianInformation": {
          "selfDefinedEthnicity": "W1",
          "observedEthnicity": "1",
          "gender": "MALE",
          "dateOfBirth": "2015-04-04",
          "personalInformation": {
            "lastName": "Brown"
          }
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-04",
          "arrestDate": "2018-12-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O"
          }
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "listNewHearing": {
    "listDefendantRequests": [
      {
        "defendantId": "DEFENDANT_ID1",
        "defendantOffences": [
          "OFFENCE_ID1"
        ]
      }
    ],
    "hearingType": {
      "id": "bf8155e1-90b9-4080-b133-bfbad895d6e4",
      "description": "Trial"
    },
    "hearingDateTimeType": "FIXED",
    "judiciary": [
      {
        "judicialRoleType": {
          "judiciaryType": "Circuit Judge"
        },
        "judicialId": "4e2df740-2822-38cc-be83-4f9cd3324ddc",
        "firstName": "Nicola Jane",
        "lastName": "Smith"
      }
    ],
    "courtCentre": {
      "id": "89592405-c29b-3706-b1d3-b1dd3a08b227",
      "name": "Blackfriars Crown Court",
      "roomId": "60853c27-8a9d-349a-aeb5-7f5049a774dd",
      "roomName": "Courtroom 02"
    },
    "estimatedMinutes": 7560,
    "specialRequirements": [
      "1",
      "11",
      "3"
    ],
    "earliestStartDateTime": "2024-04-25T09:15:00Z",
    "jurisdictionType": "CROWN"
  },
  "channel": "MCC",
  "migrationSourceSystem": {
    "migrationSourceSystemName": "XHIBIT",
    "migrationSourceSystemCaseIdentifier": "XHIBIT-2-HEARINGS"
  }
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution1.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "cpsOrganisationId": "2013c181-7458-4fb2-a637-b596fbe0e781",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "summonsCode": "A",
    "caseId": "CASE-ID",
    "initiationCode": "INITIATION_CODE",
    "prosecutorCaseReference": "CASE-URN",
    "policeSystemId": "00101PoliceCaseSystem",
    "caseMarkers": [
      {
        "markerTypeCode": "ABC",
        "markerTypeDescription": "",
        "markerTypeId": "2013c181-7458-4fb2-a637-b596fbe0e781"
      }
    ],
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    },
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "asn": "ASN_ID1",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1",
      "pncIdentifier": "2099/1234567L",
      "croNumber": "SF20/123456M",
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "numPreviousConvictions": 3,
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "FIRST_NAME_1",
          "lastName": "LAST_NAME_1",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE",
          "dateOfBirth": "DATE_OF_BIRTH_1"
        },
        "bailConditions": "Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should buy coffee every day for commissioner Vijay. Defendants Saz and Antonio should. 2500 characters",
        "parentGuardianInformation": {
          "selfDefinedEthnicity": "W1",
          "observedEthnicity": "1",
          "gender": "MALE",
          "dateOfBirth": "2015-04-04",
          "personalInformation": {
            "lastName": "Brown"
          }
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-04",
          "arrestDate": "2018-12-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O",
            "vehicleRegistrationMark": "AA11 ABC"
          },
          "plea": {
            "pleaDate": "2018-09-11",
            "pleaValue": "GUILTY"
          },
          "verdict": {
            "verdictDate": "2018-09-12",
            "verdictType": {
              "id": "c4ca4238-a0b9-3382-8dcc-509a6f75849b",
              "category": "Guilty",
              "categoryType": "GUILTY"
            }
          }
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "id": "DEFENDANT_ID2",
      "asn": "ASN_ID2",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE2",
      "individualAliases": [
        {
          "title": "Baron",
          "firstName": "John",
          "givenName2": "James",
          "givenName3": "Jerry",
          "lastName": "Smith"
        },
        {
          "title": "Baroness",
          "firstName": "John",
          "lastName": "Smith"
        }
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "bailConditions": "bailConditions",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "FIRST_NAME_2",
          "lastName": "LAST_NAME_2",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "bailConditions": "bailConditions",
        "selfDefinedInformation": {
          "gender": "MALE",
          "dateOfBirth": "DATE_OF_BIRTH_2"
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID2",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-10-10",
          "arrestDate": "2018-10-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Toyota",
          "vehicleRegistrationMark": "BB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "CPPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-requisition-all-fields.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "caseId": "CASE-ID",
    "initiationCode": "Q",
    "prosecutorCaseReference": "CASE-URN",
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    }
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1",
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "numPreviousConvictions": 3,
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        },
        "parentGuardianInformation": {
          "selfDefinedEthnicity": "W1",
          "observedEthnicity": "1",
          "gender": "MALE",
          "dateOfBirth": "2015-04-04",
          "personalInformation": {
            "lastName": "Brown"
          }
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2019-01-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O",
            "vehicleRegistrationMark": "AA11 ABC"
          }
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "id": "DEFENDANT_ID2",
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE2",
      "individualAliases": [
        {
          "title": "Baron",
          "firstName": "John",
          "givenName2": "James",
          "givenName3": "Jerry",
          "lastName": "Smith"
        },
        {
          "title": "Baroness",
          "firstName": "John",
          "lastName": "Smith"
        }
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID2",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2019-01-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Toyota",
          "vehicleRegistrationMark": "BB11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}
