=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-domain/prosecutioncasefile-domain-value-schema/src/main/resources/json/schema/prosecution.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/prosecution.json",
  "type": "object",
  "description": "Prosecution Case File Details",
  "properties": {
    "caseDetails": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/case-details.json"
    },
    "defendants": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/defendant.json"
      }
    },
    "channel": {
      "type": "string",
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/pcf-definitions.json#/definitions/channel"
    },
    "listNewHearing": {
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/hearingRequest.json"
    },
    "migrationSourceSystem": {
      "$ref": "http://justice.gov.uk/core/courts/migrationSourceSystem.json"
    },
    "externalId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid",
      "description": "ID originating from the client (SPI or CPPI) for referencing the original message"
    },
    "isCivil": {
      "description": "Marker to indicate that MoJ offence reference data should be used as opposed to criminal offence reference data",
      "type": "boolean"
    },
    "isGroupMember": {
      "description": "Indicates if a case is part of a group of cases within the hearing",
      "type": "boolean"
    },
    "isGroupMaster": {
      "description": "Indicates which case within a group (isGroupMember = true) is the master and should be returned by the backend to the UI",
      "type": "boolean"
    }
  },
  "required": [
    "caseDetails",
    "defendants",
    "channel"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-mcc-trial-indicated-guilty-plea-libra.json
{
  "caseDetails": {
    "dateReceived": "2018-07-10",
    "trialReceiptType": "Transfer",
    "eitherWayType": "Election of accused",
    "courtReceivedFromCode": "B02NM03",
    "courtReceivedToCode": "B04NM04",
    "classOfCase": "Class 1",
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Mr"
      }
    },
    "summonsCode": "A",

    "initiationCode": "O",

    "prosecutor": {
      "prosecutingAuthority": "prosAut"
    },
    "policeForceCode": "1"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "pncIdentifier": "2099/1234567L",
      "croNumber": "SF20/123456M",
      "prosecutorDefendantReference": "TFL001Defendant01",
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "custodyTimeLimit": "2050-02-04",
      "numPreviousConvictions": 3,
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001",
        "hearingTypeCode": "FPTP"
      },
      "individual": {
        "personalInformation": {
          "title": "Mr",
          "firstName": "John",
          "lastName": "Smith",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        },
        "bailConditions": "bailConditions",
        "parentGuardianInformation": {
          "selfDefinedEthnicity": "W1",
          "observedEthnicity": "1",
          "gender": "MALE",
          "dateOfBirth": "2015-04-04",
          "personalInformation": {
            "lastName": "Brown"
          }
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-04",
          "arrestDate": "2018-12-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleRelatedOffence": {
            "vehicleCode": "O"
          },
          "plea": {
            "pleaDate": "2018-09-11",
            "pleaValue": "INDICATED_GUILTY"
          },
          "convictingCourtCode": "B02NM03"
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "id": "DEFENDANT_ID2",
      "pncIdentifier": "2099/1234567L",
      "croNumber": "SF20/123456M",
      "individualAliases": [
        {
          "title": "Mr",
          "firstName": "John",
          "givenName2": "James",
          "givenName3": "Jerry",
          "lastName": "Smith"
        },
        {
          "title": "Miss",
          "firstName": "John",
          "lastName": "Smith"
        }
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "bailConditions": "bailConditions",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Mr",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "bailConditions": "bailConditions",
        "selfDefinedInformation": {
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID2",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-10-10",
          "arrestDate": "2018-10-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          }
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "MCC",
  "migrationSourceSystem": {
    "migrationSourceSystemName": "LIBRA",
    "migrationSourceSystemCaseIdentifier": "LIBRA-2-HEARINGS"
  }
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-civil-summons-civil-offence.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "summonsCode": "SUMMONS_CODE",
    "caseId": "CASE-ID",
    "initiationCode": "S",
    "prosecutorCaseReference": "CASE-URN",
    "caseMarkers": [{
      "markerTypeCode": "ABC",
      "markerTypeDescription": "Child Abuse",
      "markerTypeId": "2013c181-7458-4fb2-a637-b596fbe0e781"
    }],
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "B01NM00"
    }
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "documentationLanguage": "E",
      "hearingLanguage": "W",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "occupation": "Software Developer",
          "occupationCode": 43,
          "address": {
            "address1": "66 Exeter Street",
            "address2": "line 2",
            "address3": "line 3",
            "address4": "line 4",
            "address5": "line 5",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "work": "020111222",
            "home": "020111223",
            "mobile": "07572222943",
            "primaryEmail": "scrooge.mcduck@mail.com",
            "secondaryEmail": "scrooge.mcduck2@mail.com"
          }
        },
        "selfDefinedInformation": {
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceId": "032575aa-85e7-11e9-bc42-526af7764f64",
          "offenceCode": "OFCODE12",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "arrestDate": "2015-03-03",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          }
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "CHANNEL_TYPE",
  "externalId": "EXTERNAL_ID",
  "isCivil": true
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-requisition-mandatory-fields.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "caseId": "CASE-ID",
    "initiationCode": "Q",
    "prosecutorCaseReference": "CASE-URN",
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    }
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "aliasForCorporate": [
        "FakeCompany",
        "RealCompany"
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "organisationName": "Ministry of Justice",
      "selfDefinedEthnicity": "W1",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2019-01-10",
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          }
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/stub-data/prosecutioncasefile.command.initiate-sjp-prosecution.json
{
  "caseDetails": {
    "caseId": "${case.id}",
    "prosecutorCaseReference": "${case.urn}",
    "originatingOrganisation": "123",
    "cpsOrganisation": "A30AB00",
    "initiationCode": "J",
    "prosecutor": {
      "prosecutingAuthority": "${prosecutor.prosecutingAuthority:-GAEAA01}",
      "informant": "Adam"
    }
  },
  "defendants": [
    {
      "id": "${defendant.id}",
      "appliedProsecutorCosts": 200,
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "prosecutorDefendantReference": "TFL001Defendant01",
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {
            "home": "0207 000 0000",
            "mobile": "11111 111 111",
            "primaryEmail": "primary@email.com",
            "secondaryEmail": "secondary@email.com",
            "work": "0207 111 1111"
          }
        },
        "selfDefinedInformation": {
          "ethnicity": "W1",
          "gender": "MALE",
          "dateOfBirth": "${defendant.dob:-1990-01-01}",
          "nationality": "${defendant.nationality:-GBR}"
        },
        "nationalInsuranceNumber": "AB123456C"
      },
      "individualAliases": [
        {
          "title": "Mr",
          "firstName": "X",
          "lastName": "Alias1"
        },
        {
          "title": "Mr",
          "firstName": "Y",
          "lastName": "Alias2"
        }
      ],
      "offences": [
        {
          "offenceCode": "${offence.code:-OFCODE12}",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "${offence.committedDate:-2017-11-10}",
          "offenceDateCode": 1,
          "offenceWording": "Duty not paid",
          "chargeDate": "${offence.chargeDate:-2018-02-01}",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "${offence.alcoholRelatedOffence.alcoholLevelMethod:-A}",
            "alcoholLevelAmount": 100
          },
          "backDuty": 340.31,
          "backDutyDateFrom": "2018-04-30",
          "backDutyDateTo": "2018-05-30",
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AB11 ABC",
          "prosecutorOfferAOCP": true
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "${channel}",
  "externalId": "${external.id}"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-api/src/raml/json/prosecutioncasefile.command.initiate-prosecution.json
{
  "caseDetails": {
    "originatingOrganisation": "cps",
    "summonsCode": "summonsCode",
    "statementOfFacts": "statementOfFacts",
    "statementOfFactsWelsh": "statementOfFactsWelsh",
    "caseId": "51cac7fb-387c-4d19-9c80-8963fa8cf222",
    "initiationCode": "H",
    "prosecutorCaseReference": "TVL55117DFXXV",
    "prosecutor": {
      "prosecutingAuthority": "GAEAA01",
      "informant": "Adam"
    }
  },
  "defendants": [
    {
    "documentationLanguage": "W",
    "hearingLanguage": "W",
    "individual": {
      "personalInformation": {
        "title": "Baron",
        "firstName": "John",
        "lastName": "Smith",
        "address": {
          "address1": "armagaddon house",
          "postcode": "M60 1NW"
        },
        "contactDetails": {}
      },
      "selfDefinedInformation": {
        "ethnicity": "white",
        "gender": "MALE"
      }
    },
      "initialHearing": {
        "courtHearingLocation" : "abcd",
        "dateOfHearing": "02-04-1978",
        "timeOfHearing": "9:05",
        "roomId": "af510310-b85f-4a4e-b0b3-9a4ae4cc9cb1",
        "roomName": "Hill East",
        "hearingListingDirection": "Special Need required",
        "hearingDuration": 60,
        "hearingLanguage": "W"
      },
      "offences": [
        {
          "offenceCode": "CA03013",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2015-04-04",
          "laidDate": "2015-04-04",
          "appliedCompensation": 200
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "individual": {
        "personalInformation": {
          "title": "Baron",
          "firstName": "John",
          "lastName": "Smith",
          "address": {
            "address1": "armagaddon house",
            "postcode": "M60 1NW"
          },
          "contactDetails": {}
        },
        "selfDefinedInformation": {
          "ethnicity": "white",
          "gender": "MALE"
        }
      },
      "offences": [
        {
          "offenceCode": "DA03014",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2015-04-04",
          "appliedCompensation": 200
        }
      ],
      "postingDate": "2018-09-10"
    }
    ],
  "isCivil": true,
  "isGroupMember": false,
  "isGroupMaster": false,
  "channel": "SPI",
  "externalId": "51cac7fb-387c-4d19-9c80-8963fa8cf333"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-command/prosecutioncasefile-command-api/src/test/resources/json/initiateSjpProsecutionWithProsecutionAuthorityIdOnly.json
{
  "caseDetails": {
    "caseId": "51cac7fb-387c-4d19-9c80-8963fa8cf222",
    "prosecutorCaseReference": "BED45615",
    "initiationCode": "J",
    "isRetrial": false,
    "prosecutor": {
      "prosecutionAuthorityId": "927709cd-712f-36bf-b469-6dddca06272d"
    }
  },
  "defendants": [{
    "id": "fb61fb76-3eee-4d16-844c-09664eac05d6",
    "documentationLanguage": "E",
    "hearingLanguage": "E",
    "individual": {
      "personalInformation": {
        "title": "MR",
        "firstName": "John",
        "lastName": "Smith",
        "address": {
          "address1": "Address line 1",
          "address2": "Locket Road",
          "postcode": "HA3 7NR"
        },
        "contactDetails": {
          "primaryEmail": "test@example.com",
          "work": "07574954021"
        }
      },
      "selfDefinedInformation": {
        "gender": "NOT_SPECIFIED"
      }
    },
    "asn": "0800PP0100000000021H",
    "offences": [
      {
        "offenceId": "bd916661-bce5-477c-a91d-b24b85367fa8",
        "offenceCode": "CL67011",
        "offenceSequenceNumber": 1,
        "offenceCommittedDate": "2026-08-05",
        "offenceDateCode": 1,
        "offenceWording": "Sample offence wording",
        "chargeDate": "2026-08-05",
        "offenceLocation": "London",
        "appliedCompensation": 200,
        "aocpEligible": false,
        "modeOfTrialDerived": "Indictable"
      }
    ],
    "appliedProsecutorCosts": 100,
    "postingDate": "2026-08-07"
  }],
  "isCivil": false,
  "channel": "%s"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-corporate-with-new-defendant.json
{
  "caseDetails": {
    "originatingOrganisation": "B01NM00",
    "cpsOrganisation": "A30AB00",
    "otherPartyOfficerInCase": {
      "personalInformation": {
        "address": {
          "address1": "101",
          "address2": "56Police House",
          "address3": "Letsby Avenue",
          "address4": "Avon",
          "postcode": "HA1 2ER"
        },
        "contactDetails": {
          "primaryEmail": "vegaoic@test.dom",
          "work": "0117911911"
        },
        "firstName": "Vega",
        "lastName": "OIC",
        "title": "Baron"
      },
      "policeOfficerRank": "Constable"
    },
    "summonsCode": "A",
    "caseId": "CASE-ID",
    "initiationCode": "C",
    "prosecutorCaseReference": "CASE-URN",
    "caseMarkers": [
      {
        "markerTypeCode": "ABC",
        "markerTypeDescription": "Child Abuse",
        "markerTypeId": "2013c181-7458-4fb2-a637-b596fbe0e781"
      }
    ],
    "prosecutor": {
      "informant": "informant",
      "prosecutingAuthority": "prosAut"
    }
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "aliasForCorporate": [
        "FakeCompany",
        "RealCompany"
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "organisationName": "Ministry of Justice",
      "selfDefinedEthnicity": "W1",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID1",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-10",
          "arrestDate": "2018-11-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AA11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    },
    {
      "id": "DEFENDANT_ID2",
      "aliasForCorporate": [
        "FakeCompany",
        "RealCompany"
      ],
      "documentationLanguage": "W",
      "hearingLanguage": "W",
      "custodyStatus": "B",
      "prosecutorDefendantReference" : "A1",
      "initialHearing": {
        "courtHearingLocation": "C55BN00",
        "dateOfHearing": "2050-02-04",
        "timeOfHearing": "09:05:01.001"
      },
      "organisationName": "Ministry of Justice2",
      "selfDefinedEthnicity": "W1",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "OFFENCE_ID2",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceLocation": "Croydon",
          "offenceWording": "TV Licence not paid",
          "chargeDate": "2018-12-10",
          "arrestDate": "2018-11-10",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          },
          "vehicleMake": "Ford",
          "vehicleRegistrationMark": "AA11 ABC"
        }
      ],
      "postingDate": "2018-09-10"
    }
  ],
  "channel": "SPI",
  "externalId": "EXTERNAL_ID"
}

=== hmcts/cpp-context-prosecution-casefile/prosecutioncasefile-integration-test/src/test/resources/command-json/prosecutioncasefile.command.initiate-cc-prosecution-with-civil-offence-location-required.json
{
  "caseDetails": {
    "initiationCode": "O",
    "prosecutor": {
      "prosecutingAuthority": "prosAut"
    },
    "originatingOrganisation": "GAFTL00",
    "dateReceived": "DATE_RECEIVED"
  },
  "defendants": [
    {
      "id": "DEFENDANT_ID1",
      "custodyStatus": "B",
      "individual": {
        "personalInformation": {
          "address": {
            "address1": "340",
            "address2": "8009 Camden Throughway",
            "postcode": "SW11 1JU"
          },
          "title": "Mr",
          "firstName": "TyshawnTEST",
          "lastName": "O'Reilly"
        },
        "selfDefinedInformation": {
          "dateOfBirth": "1970-11-11",
          "gender": "NOT_SPECIFIED"
        }
      },
      "documentationLanguage": "E",
      "hearingLanguage": "E",
      "offences": [
        {
          "offenceCode": "OFCODE12",
          "offenceId": "2013c181-7458-4fb2-a637-b596fbe0e792",
          "offenceSequenceNumber": 1,
          "offenceCommittedDate": "2018-09-10",
          "offenceCommittedEndDate": "2018-10-10",
          "offenceDateCode": 1,
          "offenceWording": "TV Licence not paid",
          "arrestDate": "2015-03-04",
          "appliedCompensation": 200,
          "alcoholRelatedOffence": {
            "alcoholLevelMethod": "A",
            "alcoholLevelAmount": 100
          }
        }
      ],
      "initialHearing": {
        "hearingDuration": 20,
        "hearingLanguage": "E",
        "dateOfHearing": "DATE_OF_HEARING",
        "timeOfHearing": "11:11:00.000",
        "courtHearingLocation": "B01LY00",
        "roomId": "9e4932f7-97b2-3010-b942-ddd2624e4dd8"
      },
      "prosecutorDefendantReference": "DEFENDANT_REFERENCE1"
    }
  ],
  "channel": "CIVIL",
  "isCivil": true
}
